package Cars;
public class TrafficLights{
 public static void main(String[] args) throws InterruptedException
 {
   Object[] lanes = new Object[12];
   System.out.println("Processing...");
   GreenLight startOne=null;
   GreenLight startTwo=null;
   GreenLight startThree=null;
   GreenLight startFour=null;
   GreenLight startFive=null;
   GreenLight startSix=null;
   GreenLight startSeven=null;
   GreenLight startEight=null;
   GreenLight StartOne=null;
   GreenLight StartTwo=null;
   GreenLight StartThree=null;
   GreenLight StartFour=null;
   while(true){
    Lanes one = new Lanes("East straight lane");
    Lanes two = new Lanes("West straight lane");
    Lanes One = new Lanes("East right turn lane");
    Lanes Two = new Lanes("West right turn lane");
    one.start();
    two.start();
    One.start();
    Two.start();
    one.join();
    two.join();
    One.join();
    Two.join();
    lanes[0]=one.getCars();
    lanes[1]=two.getCars();
    lanes[2]=One.getCars();
    lanes[3]=Two.getCars();
    startOne  = new GreenLight(0,lanes);
    startTwo = new GreenLight(1,lanes);
    StartOne  = new GreenLight(2,lanes);
    StartTwo = new GreenLight(3,lanes);
    startOne.start();
    startTwo.start();
    StartOne.start();
    StartTwo.start();
    Lanes three = new Lanes("South straight lane");
    Lanes four = new Lanes("North  straight lane");
    Lanes Three = new Lanes("South right turn lane");
    Lanes Four = new Lanes("North  right trun lane");
    three.start();
    four.start();
    Three.start();
    Four.start();
    startOne.join();
    startTwo.join();
    StartOne.join();
    StartTwo.join();
    three.join();
    four.join();
    Three.join();
    Four.join();
    lanes[4]=three.getCars();
    lanes[5]=four.getCars();
    lanes[6]=Three.getCars();
    lanes[7]=Four.getCars();
    startThree  = new GreenLight(4,lanes);
    startFour = new GreenLight(5,lanes);
    StartThree  = new GreenLight(6,lanes);
    StartFour = new GreenLight(7,lanes);
    startThree.start();
    startFour.start();
    StartThree.start();
    StartFour.start();
    Lanes five = new Lanes("East left turn lane");
    Lanes six = new Lanes("West left turn lane");
    five.start();
    six.start();
    startThree.join();
    startFour.join();
    StartThree.join();
    StartFour.join();
    five.join();
    six.join();
    lanes[8]=five.getCars();
    lanes[9]=six.getCars();
    startFive  = new GreenLight(8,lanes);
    startSix = new GreenLight(9,lanes);
    startFive.start();
    startSix.start();
    Lanes seven = new Lanes("South left turn lane");
    Lanes eight = new Lanes("North left turn lane");
    seven.start();
    eight.start();
    startFive.join();
    startSix.join();
    seven.join();
    eight.join();
    lanes[10]=seven.getCars();
    lanes[11]=eight.getCars();
    startSeven  = new GreenLight(10,lanes);
    startEight = new GreenLight(11,lanes);
    startSeven.start();
    startEight.start();
    startSeven.join();
    startEight.join();
   }
  }
}
